# Site settings
title: Ionic Team - Basic Course
description: A blog about learning ionic
baseurl: "/"

# User settings
username: ionic-training
user_description: Ionic Team in SH
email: training@ionicteam-de
github_username:  ionic-training

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
